
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "client1.box"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  config.vm.network :private_network, ip: "192.168.70.45"
  config.vm.synced_folder "../scripts/", "/srv/scripts"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "512",
    ]
  end

  config.vm.provision "shell", inline: 'bash /srv/scripts/setup-k3s.sh'
  config.vm.provision "shell", inline: 'bash /srv/scripts/startup-client.sh'

end
